### ISSUE TITLE
Nao update is not working

### ISSUE THREAD

**Issue by CyrilleB79** [sharkboyto/nao#39]
Hello

I have seen on the mailing list that NAO has been updated for 2023.1.
However, manually checking for an update gives me an error dialog box and I cannot update.

Since I may have broken my NVDA config with other test actions, I have eventually downloaded and installed the update. The installation is OK. But trying to update again manually still gives the error message instead of the "No update" message. There is no further information in the log.

Finally, I have made a test on NVDA 2023.1rc1 and a brand new empty config folder. I have installed NAO successfully. But the manual update still gives an error message instead of the "No update" message.

**Comment by CyrilleB79** [comment]
Also, I do not know if it is related.

But today, this error popped up in my log without any action from my end (no manual update).

```
ERROR - logHandler._threadExceptHook (08:40:53.462) - Thread-457 (_check_proc) (12004):
Exception in thread Thread-457 (_check_proc):
Traceback (most recent call last):
  File "C:\Users\CB232690\AppData\Roaming\nvda\addons\nao\globalPlugins\nao\framework\generic\http.py", line 156, in json_post
    response = urllib.request.urlopen(req, obj, context=ctx)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "urllib\request.pyc", line 216, in urlopen
  File "urllib\request.pyc", line 519, in open
  File "urllib\request.pyc", line 536, in _open
  File "urllib\request.pyc", line 496, in _call_chain
  File "urllib\request.pyc", line 1391, in https_open
  File "urllib\request.pyc", line 1352, in do_open
  File "http\client.pyc", line 1390, in getresponse
  File "http\client.pyc", line 325, in begin
  File "http\client.pyc", line 286, in _read_status
  File "socket.pyc", line 706, in readinto
  File "ssl.pyc", line 1314, in recv_into
  File "ssl.pyc", line 1166, in read
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "C:\Users\CB232690\AppData\Roaming\nvda\addons\nao\globalPlugins\nao\framework\generic\updates.py", line 155, in _check_proc
    response = json_post(self._url, cb_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB232690\AppData\Roaming\nvda\addons\nao\globalPlugins\nao\framework\generic\http.py", line 167, in json_post
    elif isinstance(e, IOError) and isinstance(e.reason, ssl.SSLCertVerificationError) and e.reason.reason == "CERTIFICATE_VERIFY_FAILED":
                                               ^^^^^^^^
AttributeError: 'TimeoutError' object has no attribute 'reason'
```
